=== ISO-TC211/UML-Best-Practices/DocumentationOfUMLModels/ShapeChange/FC/FC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="FeatureCatalogue">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="scope" type="xs:string"/>
				<xs:element name="versionNumber" type="xs:string"/>
				<xs:element name="versionDate" type="xs:string"/>
				<xs:element name="producer" type="xs:string"/>
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="ApplicationSchema"/>
					<xs:element ref="Package"/>
					<xs:element ref="FeatureType"/>
					<xs:element ref="FeatureAttribute"/>
					<xs:element ref="FeatureRelationship"/>
					<xs:element ref="FeatureOperation"/>
					<xs:element ref="RelationshipRole"/>
					<xs:element ref="Value"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ApplicationSchema">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="versionNumber" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Package">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="code" type="xs:string" minOccurs="0"/>
				<xs:element name="diagram" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="src" type="xs:anyURI" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="parent" type="ReferenceType"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FeatureType">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="code" type="xs:string" minOccurs="0"/>
				<xs:element name="subtypeOf" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="characterizedBy" type="ReferenceType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="package" type="ReferenceType" minOccurs="0"/>
				<xs:element name="type" type="xs:string" minOccurs="0"/>
				<xs:element name="lastChange" type="xs:string" minOccurs="0"/>
				<xs:element name="diagram" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="src" type="xs:anyURI" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="constraint" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FeatureAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="cardinality" type="xs:string" minOccurs="0"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="code" type="xs:string" minOccurs="0"/>
				<xs:element name="voidable" type="xs:boolean" minOccurs="0"/>
				<xs:element name="lastChange" type="xs:string" minOccurs="0"/>
				<xs:element name="ValueDataType" type="ReferenceType"/>
				<xs:element name="ValueDomainType" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="enumeratedBy" type="ReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FeatureRelationship">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="roles" type="ReferenceType" minOccurs="0" maxOccurs="2"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FeatureOperation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="objectFeatureTypeNames" type="ReferenceType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="RelationshipRole">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="cardinality" type="xs:string" minOccurs="0"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="code" type="xs:string" minOccurs="0"/>
				<xs:element name="voidable" type="xs:boolean" minOccurs="0"/>
				<xs:element name="lastChange" type="xs:string" minOccurs="0"/>
				<xs:element name="FeatureTypeIncluded" type="ReferenceType"/>
				<xs:element name="relation" type="ReferenceType"/>
				<xs:element name="InverseRole" type="ReferenceType" minOccurs="0"/>
				<xs:element name="constraints" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="orderIndicator">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="0"/>
							<xs:enumeration value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Value">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="label" type="xs:string"/>
				<xs:element name="code" type="xs:string" minOccurs="0"/>
				<xs:element name="definition" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="lastChange" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ReferenceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="idref" type="xs:IDREF"/>
				<xs:attribute name="category" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== ISO-TC211/UML-Best-Practices/DocumentationOfUMLModels/ShapeChange/output1/INPUT/19135.tmp.xml
<?xml version="1.0" encoding="Windows-1252"?><?xml-stylesheet type='text/xsl' href='./html.xsl'?><!--Feature catalogue created using ShapeChange--><FeatureCatalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FC.xsd">
  <name>ISO 19135-1 Procedures for Registration</name>
  <scope>This part of ISO 19135 specifies procedures to be followed in establishing, maintaining and publishing registers of unique, unambiguous and permanent identifiers and meanings that are assigned to items of geographic information. In order to accomplish this purpose, this part of ISO 19135 specifies elements that are necessary to manage the registration of these items.</scope>
  <versionNumber>ISO/DIS 19135-1:2013</versionNumber>
  <versionDate>2013</versionDate>
  <producer>International Organisation for Standardization</producer>
  <ApplicationSchema id="_P416">
    <name>ISO 19135-1 Procedures for Registration - Extended schema</name>
    <taggedValues/>
  </ApplicationSchema>
  <FeatureType id="_C2806">
    <name>RE_AdditionInformation</name>
    <definition>The subclass RE_AdditionInformation contains management information about a proposal to add an item to a register.</definition>
    <subtypeOf idref="_C2793">RE_ProposalManagementInformation</subtypeOf>
    <characterizedBy idref="_AS2429"/>
    <package idref="_P416"/>
    <type>Object Type</type>
    <taggedValues/>
    <images>
      <image height="1308" id="img7" idAsInt="0" name="Fig B7 RE_AmendmentInformation, RE_ClarificationInformation and RE_AdditionInformation" relPath="images/ISO_19135-1_Procedures_for_Registration_-_Extended_schema/img7.jpg" width="1842"/>
    </images>
  </FeatureType>
  <FeatureRelationship id="__S2429">
    <name>(unbestimmt)</name>
    <roles idref="_AS2429"/>
    <roles idref="_AT2429"/>
  </FeatureRelationship>
  <RelationshipRole id="_AS2429">
    <name>item</name>
    <cardinality>1</cardinality>
    <definition>The role "addtionInformation"  identifies the class RE_AdditionInformation for addtional information about the registerItem</definition>
    <taggedValues/>
    <FeatureTypeIncluded category="object type" idref="_C2823">RE_RegisterItem</FeatureTypeIncluded>
    <relation idref="__S2429"/>
    <InverseRole idref="_AT2429"/>
    <orderIndicator>0</orderIndicator>
  </RelationshipRole>
  <RelationshipRole id="_AT2429">
    <name>additionInformation</name>
    <cardinality>1..*</cardinality>
    <definition>The role "item"  identifies the class RE_RegisterItem  for addtional nformation in the RE_AdditionalInformation</definition>
    <taggedValues/>
    <FeatureTypeIncluded category="object type" idref="_C2806">RE_AdditionInformation</FeatureTypeIncluded>
    <relation idref="__S2429"/>
    <InverseRole idref="_AS2429"/>
    <orderIndicator>0</orderIndicator>
  </RelationshipRole>
  <FeatureType id="_C2791">
    <name>RE_AlternativeExpression</name>
    <definition>The class RE_AlternativeExpression is a data type used to provide information about a register item in an alternative language. Subclasses of</definition>
    <definition>RE_AlternativeExpression may be specified in order to add additional attributes appropriate for particular item classes.</definition>
    <definition/>
    <definition>EXAMPLE A specification for a metadata element register could identify a subclass of RE_AlternativeExpression that would include the data dictionary fields specified in ISO 19115-1(obligation/condition, data type, and domain) as additional attributes.</definition>
    <characterizedBy idref="_A2791_5131"/>
    <characterizedBy idref="_A2791_5132"/>
    <characterizedBy idref="_A2791_5133"/>
    <characterizedBy idref="_A2791_5134"/>
    <characterizedBy idref="_AT2441"/>
    <package idref="_P416"/>
    <type>Data Type</type>
    <taggedValues/>
  </FeatureType>
  <FeatureAttribute id="_A2791_5131">
    <name>name</name>
    <cardinality>1</cardinality>
    <definition>The attribute "name"&lt;i&gt; &lt;/i&gt;shall be represented as a CharacterString whose content meets the requirements of RE_RegisterItem.name&lt;i&gt; &lt;/i&gt;except that the applicable locale shall be that specified in RE_AlternativeExpression.locale.</definition>
    <taggedValues/>
    <ValueDataType>CharacterString</ValueDataType>
  </FeatureAttribute>
  <FeatureAttribute id="_A2791_5132">
    <name>definition</name>
    <cardinality>0..1</cardinality>
    <definition>The attribute "definition"&lt;i&gt; &lt;/i&gt;shall be represented as a CharacterString whose content meets the requirements of RE_RegisterItem.definition&lt;i&gt; &lt;/i&gt;except that the applicable locale shall be that specified in RE_AlternativeExpression.locale.</definition>
    <taggedValues/>
    <ValueDataType>CharacterString</ValueDataType>
  </FeatureAttribute>
  <FeatureAttribute id="_A2791_5133">
    <name>description</name>
    <cardinality>0..1</cardinality>
    <definition>The attribute description&lt;i&gt; &lt;/i&gt;shall be represented as a CharacterString whose content meets the requirements of RE_RegisterItem.description&lt;i&gt; &lt;/i&gt;except that the applicable locale shall be that specified in RE_AlternativeExpression.locale.</definition>
    <taggedValues/>
    <ValueDataType>CharacterString</ValueDataType>
  </FeatureAttribute>
  <FeatureAttribute id="_A2791_5134">
    <name>fieldOfApplication</name>
    <cardinality>0..1</cardinality>
    <definition>The attribute fieldOfApplication&lt;i&gt; &lt;/i&gt;shall be represented as a set of instances of RE_FieldOfApplication whose content meets the requirements of RE_RegisterItem.fieldOfApplication&lt;i&gt; &lt;/i&gt;except that the applicable locale shall be that specified in RE_AlternativeExpression.locale</definition>
    <taggedValues/>
    <ValueDataType>Set&lt;RE_FieldOfApplication&gt;</ValueDataType>
  </FeatureAttribute>
  <FeatureRelationship id="__T2441">
    <name>(unbestimmt)</name>
    <roles idref="_AT2441"/>
    <roles idref="_AS2441"/>
  </FeatureRelationship>
  <RelationshipRole id="_AT2441">
    <name>locale</name>
    <cardinality>1</cardinality>
    <definition>The role "expression"  identifies the class RE_AlternativeExpression for language information as specified in RE_Locale</definition>
    <taggedValues/>
    <FeatureTypeIncluded category="object type" idref="_C2824">RE_Locale</FeatureTypeIncluded>
    <relation idref="__T2441"/>
    <InverseRole idref="_AS2441"/>
    <orderIndicator>0</orderIndicator>
  </RelationshipRole>
  <RelationshipRole id="_AS2441">
    <name>expression</name>
    <cardinality>0..*</cardinality>
    <definition>The role "locale"  identifies the class RE_Locale for further information about the language used for the alternative expression</definition>
    <taggedValues/>
    <FeatureTypeIncluded category="object type" idref="_C2791">RE_AlternativeExpression</FeatureTypeIncluded>
    <relation idref="__T2441"/>
    <InverseRole idref="_AT2441"/>
    <orderIndicator>0</orderIndicator>
  </RelationshipRole>
  <FeatureType id="_C2821">
    <name>RE_AlternativeName</name>
    <definition>The class RE_AlternativeName is a data type used to provide the name of an item class in an alternative language.</definition>
    <characterizedBy idref="_A2821_5188"/>
    <characterizedBy idref="_AT2406"/>
    <package idref="_P416"/>
    <type>Data Type</type>
    <taggedValues/>
  </FeatureType>
  <FeatureAttribute id="_A2821_5188">
    <name>name</name>
    <cardinality>1</cardinality>
    <taggedValues/>
    <ValueDataType>CharacterString</ValueDataType>
  </FeatureAttribute>
  <FeatureRelationship id="__T2406">
    <name>(unbestimmt)</name>
    <roles idref="_AT2406"/>
    <roles idref="_AS2406"/>
  </FeatureRelationship>
  <RelationshipRole id="_AT2406">
    <name>locale</name>
    <cardinality>1</cardinality>
    <definition>The role "name" identifies that information in the class RE_Locale gives further information about the language of the name i RE_AlternativeName</definition>
    <taggedValues/>
    <FeatureTypeIncluded category="object type" idref="_C2824">RE_Locale</FeatureTypeIncluded>
    <relation idref="__T2406"/>
    <orderIndicator>0</orderIndicator>
  </RelationshipRole>
  <RelationshipRole id="_AS2406">
    <name>name</name>
    <cardinality>0..*</cardinality>
    <definition>The role "locale" identifies the class RE_Locale for further information about the name used in RE_AlternativeName</definition>
    <description>This is a non-navigable relationship role.</description>
    <taggedValues/>
    <FeatureTypeIncluded category="object type" idref="_C2821">RE_AlternativeName</FeatureTypeIncluded>
    <relation idref="__T2406"/>
    <InverseRole idref="_AT2406"/>
    <orderIndicator>0</orderIndicator>
  </RelationshipRole>
  <FeatureType id="_C2803">
    <name>RE_AmendmentInformation</name>
    <definition>The subclass RE_AmendmentInformation contains management information about a proposal to amend an item in a register.</definition>
    <subtypeOf idref="_C2793">RE_ProposalManagementInformation</subtypeOf>
    <characterizedBy idref="_A2803_5162"/>
    <characterizedBy idref="_AS2432"/>
    <package idref="_P416"/>
    <type>Object Type</type>
    <taggedValues/>
    <images>
      <image height="1308" id="img7" idAsInt="2" name="Fig B7 RE_AmendmentInformation, RE_ClarificationInformation and RE_AdditionInformation" relPath="images/ISO_19135-1_Procedures_for_Registration_-_Extended_schema/img7.jpg" width="1842"/>
    </images>
  </FeatureType>
  <FeatureAttribute id="_A2803_5162">
    <name>amendmentType</name>
    <cardinality>1</cardinality>
    <definition>The attribute "amendmentType"&lt;i&gt; &lt;/i&gt;shall be represented as an instance of RE_AmendmentType that identifies the type of amendment proposed.</definition>
    <taggedValues/>
    <ValueDataType category="enumeration">RE_AmendmentType</ValueDataType>
    <ValueDomainType>1</ValueDomainType>
    <enumeratedBy idref="_A2800_5160"/>
    <enumeratedBy idref="_A2800_5161"/>
