=== ISO-TC211/UML-Best-Practices/DocumentationOfUMLModels/ShapeChange/ShapeChange/test/config/ShapeChangeConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1"
  xmlns:xi="http://www.w3.org/2001/XInclude"
  xmlns:sc="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1"
  xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  attributeFormDefault="unqualified" version="1.1.0b1">
  <import namespace="http://www.w3.org/2001/XInclude" schemaLocation="XInclude.xsd"/>
  <element name="ShapeChangeConfiguration" type="sc:ShapeChangeConfigurationType"/>
  <complexType name="ShapeChangeConfigurationType">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element ref="sc:ShapeChangeConfiguration"/>
      <element ref="sc:input"/>
      <element ref="sc:dialog"/>
      <element ref="sc:log"/>
      <element ref="sc:transformers"/>
      <element ref="sc:targets"/>
    </choice>
  </complexType>
  <element name="input">
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:parameter"/>
        <element ref="sc:stereotypeAliases"/>
        <element ref="sc:packages"/>
        <element ref="xi:include"/>
      </choice>
      <attribute name="id" type="ID"/>
    </complexType>
  </element>
  <element name="parameter">
    <complexType>
      <attribute name="name" type="string" use="required"/>
      <attribute name="value" type="string" use="required"/>
    </complexType>
  </element>
  <element name="stereotypeAliases">
    <complexType>
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:StereotypeAlias"/>
      </sequence>
    </complexType>
  </element>
  <element name="StereotypeAlias" type="sc:StereotypeAliasType"/>
  <complexType name="StereotypeAliasType">
    <sequence/>
    <attribute name="wellknown" use="required">
      <simpleType>
        <restriction base="string">
          <enumeration value=""/>
          <enumeration value="Abstract"/>
          <enumeration value="DataType"/>
          <enumeration value="FeatureType"/>
          <enumeration value="Enumeration"/>
          <enumeration value="CodeList"/>
          <enumeration value="Union"/>
          <enumeration value="BasicType"/>
          <enumeration value="Interface"/>
          <enumeration value="Type"/>
          <enumeration value="Union"/>
          <enumeration value="Application Schema"/>
          <enumeration value="Leaf"/>
          <enumeration value="Schluesseltabelle"/>
          <enumeration value="FachId"/>
          <enumeration value="ADEElement"/>
          <enumeration value="import"/>
          <enumeration value="include"/>
          <enumeration value="disjoint"/>
          <enumeration value="voidable"/>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="alias" type="string" use="required"/>
  </complexType>
  <element name="packages">
    <complexType>
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:PackageInfo"/>
      </sequence>
    </complexType>
  </element>
  <element name="PackageInfo" type="sc:PackageInfoType"/>
  <complexType name="PackageInfoType">
    <sequence/>
    <attribute name="packageName" type="string" use="required"/>
    <attribute name="nsabr" type="string"/>
    <attribute name="ns" type="string"/>
    <attribute name="xsdDocument" type="string"/>
    <attribute name="version" type="string"/>
  </complexType>
  <element name="dialog">
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:parameter"/>
      </choice>
    </complexType>
  </element>
  <element name="log">
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:parameter"/>
      </choice>
    </complexType>
  </element>
  <simpleType name="ProcessMode">
    <restriction base="string">
      <enumeration value="enabled"/>
      <enumeration value="disabled"/>
      <enumeration value="diagnostics-only"/>
    </restriction>
  </simpleType>
  <complexType name="ProcessBaseType">
    <attribute name="class" type="string" use="required"/>
    <attribute name="mode" type="sc:ProcessMode" default="enabled"/>
  </complexType>
  <element name="ProcessParameter" type="sc:ProcessParameterType"/>
  <complexType name="ProcessParameterType">
    <attribute name="name" type="string" use="required"/>
    <attribute name="value" type="string" use="required"/>
  </complexType>
  <element name="ProcessRuleSet" type="sc:ProcessRuleSetType"/>
  <complexType name="ProcessRuleSetType">
    <choice maxOccurs="unbounded" minOccurs="0">
      <element name="rule" type="sc:RuleRefType"/>
    </choice>
    <attribute name="name" type="string" use="required"/>
    <attribute name="extends" type="string"/>
  </complexType>
  <element name="ProcessMapEntry" type="sc:MapEntryType"/>
  <complexType name="TransformerType">
    <complexContent>
      <extension base="sc:ProcessBaseType">
        <choice maxOccurs="unbounded" minOccurs="0">
          <element name="parameters">
            <complexType>
              <choice maxOccurs="unbounded">
                <element ref="sc:ProcessParameter"/>
              </choice>
            </complexType>
          </element>
          <element name="rules">
            <complexType>
              <choice maxOccurs="unbounded" minOccurs="1">
                <element ref="sc:ProcessRuleSet"/>
              </choice>
            </complexType>
          </element>
          <element name="mapEntries">
            <complexType>
              <choice maxOccurs="unbounded">
                <element ref="sc:ProcessMapEntry"/>
              </choice>
            </complexType>
          </element>
          <element name="taggedValues">
            <complexType>
              <choice maxOccurs="unbounded">
                <element ref="sc:TaggedValue"/>
              </choice>
            </complexType>
          </element>
          <element ref="xi:include"/>
        </choice>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="input" type="IDREF"/>
      </extension>
    </complexContent>
  </complexType>
  <element name="transformers">
    <complexType>
      <sequence maxOccurs="unbounded" minOccurs="1">
        <element ref="sc:Transformer"/>
      </sequence>
    </complexType>
  </element>
  <element name="Transformer" type="sc:TransformerType"/>
  <element name="targets">
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:Target"/>
        <element ref="sc:TargetXmlSchema"/>
        <element ref="sc:TargetOwl"/>
      </choice>
    </complexType>
  </element>
  <element name="Target" type="sc:TargetType"/>
  <complexType name="TargetType">
    <complexContent>
      <extension base="sc:TargetBaseType">
        <choice minOccurs="0" maxOccurs="unbounded">
          <element ref="sc:targetParameter"/>
          <element ref="sc:targetParameters"/>
          <element ref="sc:rules"/>
          <element ref="sc:mapEntries"/>
          <element ref="sc:namespaces"/>
          <element ref="xi:include"/>
        </choice>
      </extension>
    </complexContent>
  </complexType>
  <element name="targetParameter">
    <complexType>
      <attribute name="name" type="string" use="required"/>
      <attribute name="value" type="string" use="required"/>
    </complexType>
  </element>
  <element name="mapEntries" type="sc:MapEntriesType"/>
  <complexType name="MapEntriesType">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element ref="sc:MapEntry"/>
      <element ref="sc:mapEntries"/>
    </choice>
  </complexType>
  <element name="MapEntry" type="sc:MapEntryType"/>
  <complexType name="MapEntryType">
    <attribute name="type" type="string" use="required"/>
    <attribute name="rule" type="string" use="required"/>
    <attribute name="targetType" type="string"/>
    <attribute name="param" type="string"/>
  </complexType>
  <element name="TargetXmlSchema" type="sc:TargetXmlSchemaType"/>
  <complexType name="TargetXmlSchemaType">
    <choice minOccurs="0" maxOccurs="unbounded">
      <element ref="sc:targetParameter"/>
      <element ref="sc:targetParameters"/>
      <element ref="sc:rules"/>
      <element ref="sc:xsdMapEntries"/>
      <element ref="sc:xmlNamespaces"/>
      <element ref="xi:include"/>
    </choice>
    <attribute name="class" type="string" use="required"
      fixed="de.interactive_instruments.ShapeChange.Target.XmlSchema.XmlSchema"/>
    <attribute name="mode" type="sc:ProcessMode" default="enabled"/>
    <attribute name="inputs" type="IDREFS"/>
  </complexType>
  <element name="namespaces">
    <complexType>
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:Namespace"/>
      </sequence>
    </complexType>
  </element>
  <element name="Namespace" type="sc:NamespaceType"/>
  <complexType name="NamespaceType">
    <sequence/>
    <attribute name="nsabr" type="string" use="required"/>
    <attribute name="ns" type="string" use="required"/>
    <attribute name="location" type="string" use="optional"/>
  </complexType>
  <element name="xmlNamespaces">
    <complexType>
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:XmlNamespace"/>
      </sequence>
    </complexType>
  </element>
  <element name="XmlNamespace" type="sc:XmlNamespaceType"/>
  <complexType name="XmlNamespaceType">
    <sequence/>
    <attribute name="nsabr" type="string" use="required"/>
    <attribute name="ns" type="string" use="required"/>
    <attribute name="location" type="string" use="optional"/>
    <attribute name="packageName" type="string"/>
  </complexType>
  <element name="xsdMapEntries">
    <complexType>
      <choice minOccurs="0" maxOccurs="unbounded">
        <element ref="sc:XsdMapEntry"/>
        <element ref="sc:xsdMapEntries"/>
      </choice>
    </complexType>
  </element>
  <element name="XsdMapEntry" type="sc:XsdMapEntryType"/>
  <complexType name="XsdMapEntryType">
    <sequence/>
    <attribute name="type" type="string" use="required"/>
    <attribute name="xsdEncodingRules" use="required">
      <simpleType>
        <list itemType="string"/>
      </simpleType>
    </attribute>
    <attribute name="xmlType" type="string"/>
    <attribute name="xmlTypeContent" default="complex">
      <simpleType>
        <restriction base="string">
          <enumeration value="simple"/>
          <enumeration value="complex"/>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="xmlTypeType" default="complex">
      <simpleType>
        <restriction base="string">
          <enumeration value="simple"/>
          <enumeration value="complex"/>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="xmlTypeNilReason" type="boolean"/>
    <attribute name="xmlElement" type="string"/>
    <attribute name="xmlPropertyType" type="string"/>
    <attribute name="xmlAttribute" type="string"/>
    <attribute name="xmlAttributeGroup" type="string"/>
    <attribute name="nsabr" type="string"/>
  </complexType>
  <element name="rules">
    <complexType>
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element name="EncodingRule" type="sc:EncodingRuleType"/>
      </sequence>
    </complexType>
  </element>
  <complexType name="RuleRefType">
    <attribute name="name" type="string" use="required"/>
  </complexType>
  <complexType name="EncodingRuleType">
    <sequence minOccurs="0" maxOccurs="unbounded">
      <element name="rule" type="sc:RuleRefType"/>
    </sequence>
    <attribute name="name" type="string" use="required"/>
    <attribute name="extends" type="string"/>
  </complexType>
  <element name="targetParameters">
    <complexType>
      <choice maxOccurs="unbounded" minOccurs="0">
        <element ref="sc:targetParameter"/>
      </choice>
    </complexType>
  </element>
  <element name="TaggedValue" type="sc:TaggedValueType"/>
  <complexType name="TaggedValueType">
    <attribute name="name" type="string" use="required"/>
    <attribute name="value" type="string"/>
    <attribute name="modelElementStereotype" type="string"/>
    <attribute name="modelElementName" type="string"/>
    <attribute name="applicationSchemaName" type="string"/>
  </complexType>
  <element name="TargetOwl" type="sc:TargetOwlType"/>
  <complexType name="TargetOwlType">
    <complexContent>
      <extension base="sc:TargetBaseType">
        <choice minOccurs="0" maxOccurs="unbounded">
          <element ref="sc:targetParameter"/>
          <element ref="sc:targetParameters"/>
          <element ref="sc:rules"/>
          <element ref="sc:mapEntries"/>
          <element ref="sc:namespaces"/>
          <element ref="sc:stereotypeMappings"/>
          <element ref="xi:include"/>
        </choice>
      </extension>
    </complexContent>
  </complexType>
  <element name="stereotypeMappings">
    <complexType>
      <sequence minOccurs="0" maxOccurs="unbounded">
        <element name="StereotypeMapping" type="sc:StereotypeMappingType"/>
      </sequence>
    </complexType>
  </element>
  <complexType name="StereotypeMappingType">
    <sequence/>
    <attribute name="wellknown" use="required">
      <simpleType>
        <restriction base="string">
          <enumeration value=""/>
          <enumeration value="Abstract"/>
          <enumeration value="DataType"/>
          <enumeration value="FeatureType"/>
          <enumeration value="Enumeration"/>
          <enumeration value="CodeList"/>
          <enumeration value="Union"/>
          <enumeration value="BasicType"/>
          <enumeration value="Interface"/>
          <enumeration value="Type"/>
          <enumeration value="Union"/>
          <enumeration value="Application Schema"/>
          <enumeration value="Leaf"/>
          <enumeration value="Schluesseltabelle"/>
          <enumeration value="FachId"/>
          <enumeration value="ADEElement"/>
          <enumeration value="import"/>
          <enumeration value="include"/>
          <enumeration value="disjoint"/>
          <enumeration value="voidable"/>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="mapsTo" type="string" use="required"/>
  </complexType>
  <complexType name="TargetBaseType">
    <complexContent>
      <extension base="sc:ProcessBaseType">
        <attribute name="inputs" type="IDREFS"/>
      </extension>
    </complexContent>
  </complexType>
</schema>

=== ISO-TC211/UML-Best-Practices/DocumentationOfUMLModels/ShapeChange/19135_doc.xml
<?xml version="1.0" encoding="UTF-8"?>
<ShapeChangeConfiguration xmlns:xi="http://www.w3.org/2001/XInclude" xmlns="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1" xmlns:sc="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.interactive-instruments.de/ShapeChange/Configuration/1.1 http://shapechange.net/resources/schema/ShapeChangeConfiguration.xsd">
	<input>
		<parameter name="inputModelType" value="EA7"/>
		<parameter name="inputFile" value="ISO19135-1_Full19135_extension.eap"/>
		<!--parameter name="appSchema" value="ISO 19135-1 Procedures for Registration"/-->
		<parameter name="publicOnly" value="true"/>
		<parameter name="checkingConstraints" value="disabled"/>
		<parameter name="sortedSchemaOutput" value="true"/>
		<parameter name="tmpDirectory" value="examples/iso/tmp"/>
		<parameter name="loadDiagrams" value="true"/>
		<parameter name="packageDiagramRegex" value="^(.*[\W]+)?Overview([\W]+.*)?$"/>
		<parameter name="classDiagramRegex" value="^(.*[\W]+)?NAME([\W]+.*)?$"/>
		<xi:include href="http://shapechange.net/resources/config/StandardAliases.xml"/>
	</input>
	<log>
		<parameter name="reportLevel" value="INFO"/>
		<parameter name="logFile" value="output1/log_19135.xml"/>
	</log>
	<targets>
		<Target class="de.interactive_instruments.ShapeChange.Target.FeatureCatalogue.FeatureCatalogue" mode="enabled">
			<targetParameter name="outputDirectory" value="output1"/>
			<targetParameter name="outputFilename" value="19135"/>
			<targetParameter name="outputFormat" value="DOCX"/>
			<targetParameter name="name" value="ISO 19135-1 Procedures for Registration"/>
			<targetParameter name="scope" value="This part of ISO 19135 specifies procedures to be followed in establishing, maintaining and publishing registers of unique, unambiguous and permanent identifiers and meanings that are assigned to items of geographic information. In order to accomplish this purpose, this part of ISO 19135 specifies elements that are necessary to manage the registration of these items."/>
			<targetParameter name="versionNumber" value="ISO/DIS 19135-1:2013"/>
			<targetParameter name="versionDate" value="2013"/>
			<targetParameter name="producer" value="International Organisation for Standardization"/>
			<targetParameter name="xsltPfad" value="http://shapechange.net/resources/xslt"/>
			<!--targetParameter name="xsltPfad" value="src/main/resources/xslt"/-->
			<targetParameter name="xsldocxFile" value="docx.xsl"/>
			<targetParameter name="featureTerm" value="Object"/>
			<targetParameter name="includeVoidable" value="false"/>		
			<targetParameter name="includeTitle" value="false"/>		
	      		<targetParameter name="includeDiagrams" value="true"/>
	      		<targetParameter name="xslTransformerFactory" value= "net.sf.saxon.TransformerFactoryImpl"/>
			<targetParameter name="docxTemplateFilePath" value="template_ISO.docx"/>
		</Target>
	</targets>
</ShapeChangeConfiguration>
